InFilePath = 'H:\PaMIr\Source code\Robinson_LPF_example\out-of-core-low-pass-filter\cmake-build-debug\test_in.dat';
OutFilePath = 'H:\PaMIr\Source code\Robinson_LPF_example\out-of-core-low-pass-filter\cmake-build-debug\test_out.dat';
inFile = fopen(InFilePath,'r');
outFile = fopen(OutFilePath,'r');
inData = fread(inFile,'double','ieee-le');
outData = fread(outFile,'double','ieee-le');
fclose(inFile);
fclose(outFile);
plot(inData);
hold on;
plot(outData);
legend("inData","outData");
figure;
options.NFFT='exact';
options.DC='ignore';
options.ampOrInt='isIntensity';
fSamp=125E6;
[spectralPowerDensityIn,frequency,phase] = spectralPowerAndFrequency(inData,fSamp,options);
plot(frequency,spectralPowerDensityIn);
hold on;
[spectralPowerDensityOut,frequency,phase] = spectralPowerAndFrequency(outData,fSamp,options);
plot(frequency,spectralPowerDensityOut);
legend("inData","outData");