//
// Created by sjoh5083 on 20/07/22.
//

#ifndef CPP_TEMPLATE_LPF_LOCKINAMPLIFIERCOLLECTION_HPP
#define CPP_TEMPLATE_LPF_LOCKINAMPLIFIERCOLLECTION_HPP

class LockInAmplifierCollection;

#endif// CPP_TEMPLATE_LPF_LOCKINAMPLIFIERCOLLECTION_HPP
